services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - '1'
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - '0'
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:16
    container_name: itops-postgres
    environment:
      POSTGRES_USER: itops
      POSTGRES_PASSWORD: itops
      POSTGRES_DB: itopsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
